# Generated by Django 5.0.3 on 2024-03-24 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realanyproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'Movie', 'verbose_name_plural': 'Movies'},
        ),
        migrations.AlterModelOptions(
            name='music',
            options={'verbose_name': 'Music', 'verbose_name_plural': 'Music'},
        ),
    ]
